### ISSUE TITLE
A chain rule term missing in FOC of investment (Week 3)

### ISSUE THREAD

**Issue by duzaichuan** [wmutschl/Computational-Macroeconomics#1]
Hi Willi, thanks for sharing your teaching material. They are excellent and very helpful!

I guess there is a missing term in week 3 NK derivation. In Q3.5, when taking the derivative w.r.t `i_t` inside the time `t` Lagrange of capital accumulation, the answer only gives a half of chain-rule terms, `q[0] * phi_iv * (iv[0]/iv[-1] -1) * (iv[0]/iv[-1])`, missing the other half `q[0]* 1/2 * (iv[0]/iv[-1] -1)^2`.

Please correct me if I was wrong about it.

Zach

Edited on question number.

**Comment by wmutschl** [comment]
Thanks for spotting this! I think I fixed it now both in the notes as well as in the codes, but please double check if you have some time.
